examples/decorator_count_exceptions.py, examples/decorator_inprogress.py, examples/decorator_timer.py, examples/example-metrics.py
fixes to apply correct code syntax highlighting to examples scripts when used in docs.
=> add script type to examples

.gitignore, Makefile, README.rst, aioprometheus/__init__.py, aioprometheus/formats/__init__.py, aioprometheus/formats/binary.py, dist/.gitignore, docs/dev/index.rst, docs/user/index.rst, requirements.dev.txt, requirements.txt, setup.py, tests/test_dist.sh, tests/test_export.py, tests/test_formats_binary.py, tests/test_pusher.py
This merge request returns the binary formatter into the project as an optional capability that is only available if the ``prometheus_metrics_proto`` package is importable.
=> return binary formatter as optional

MANIFEST.in
This project uses wheels as distribution archives. The MANIFEST.in file is not used for binary wheel artefacts which means it is no longer needed in this project.
=> Remove unused manifest file

Makefile
The ``dist.upload`` Makefile rule is broken. It calls clean which deletes the distribution, then it tries to upload a non-existant file.
=> Fix upload rule

README.rst, docs/index.rst, docs/user/index.rst, examples/decorator_count_exceptions.py, examples/decorator_inprogress.py, examples/decorator_timer.py, examples/simple-example.py
- Update documentation to describe that the ``/`` route can be used as a ``/healthz`` style indicator.
- Update examples to reflect the ability to register collectors directly with the service rather than having to access the registry within the service.
=> update docs and minor cleanups

.readthedocs.yaml, setup.py
The docs hosted on ReadTheDocs is failing due to the default configuration using Python3.5 while the project now depends on ``aiohttp`` 3.2.1 which requires a minimum of Python 3.6.
Define a configuration file for ReadTheDocs that uses Python3.6.
Also, fix a minor issue parsing the requirements file that was observed in the ``setup.py`` file.
=> add readthedocs config

docs/dev/index.rst, docs/index.rst, docs/user/index.rst, src/aioprometheus/__init__.py, src/aioprometheus/collectors.py, src/aioprometheus/formats/text.py, src/aioprometheus/histogram.py, src/aioprometheus/service.py, tests/test_decorators.py, tests/test_export.py, tests/test_formats_binary.py, tests/test_formats_text.py, tests/test_metricdict.py, tests/test_metrics.py, tests/test_negotiate.py, tests/test_pusher.py, tests/test_registry.py
The changes in this merge request should fix #28.
- Fix histogram to produce the expected cumulative results.
- Fix histogram to sort metrics placing +Inf last followed by the count and then sum.
- For consistency by report histogram values as float
- Some cosmetic docs updates.
- Bump version in preparation for a new release.
- Style formatting fixes
=> Fix histogram

README.rst, docs/index.rst, docs/user/index.rst, examples/app-example.py, examples/frameworks/aiohttp-example.py, examples/frameworks/quart-example.py, examples/frameworks/vibora-example.py, examples/simple-example.py, requirements.txt, src/aioprometheus/__init__.py, src/aioprometheus/formats/__init__.py, src/aioprometheus/formats/binary.py, src/aioprometheus/formats/text.py, src/aioprometheus/negotiator.py, src/aioprometheus/renderer.py, src/aioprometheus/service.py, tests/test_aiohttp.py, tests/test_quart.py, tests/test_renderer.py, tests/test_vibora.py
This merge request adds a metrics rendering function that makes it easier to use aioprometheus from within existing Python web framework applications, such as Vibora, Quart and aiohttp, where an existing web server is already available and there is no desire to start another server endpoint just to server Prometheus metrics. 
- The Service now makes use of the new render function.
- A test was added to check the render function.
- Tests are included that verify the render function operates as expected when used within various frameworks.
- Docs have been updated.
- Examples have been included which demonstrate how to use the render function within various frameworks.
- Some examples where updated to use a fixed port instead of an ephemeral one to simplify matching docs to example code …
=> add metrics render function

src/aioprometheus/metricdict.py
This fixes an annoying warning about importing ABCs from collections instead of collections.abc. Should be backwards compatible.
=> Fix deprecation warning about importing ABCs from collections

.travis.yml, Makefile, src/aioprometheus/__init__.py, src/aioprometheus/collectors.py, src/aioprometheus/formats/base.py, src/aioprometheus/histogram.py, src/aioprometheus/negotiator.py, src/aioprometheus/pusher.py, src/aioprometheus/registry.py, src/aioprometheus/renderer.py, tests/test_decorators.py, tests/test_export.py, tests/test_metricdict.py, tests/test_metrics.py, tests/test_negotiate.py, tests/test_pusher.py
Prepare for a new package release containing changes from #33.
- Update version to 19.10.0
- Run style formatter (updated since last release which caused quite a few minor style updates).
- Add style check rule to Makefile.
- Call style check rule from ``.travis.yml`` file. The CI step will now properly fail if the code fails code format checks.
- Modify Makefile to not call the clean rule as part of generating a new distribution package. This causes venv performing the wheel generation to be deleted causing much sadness.
=> Update for next release

README.rst, docs/dev/index.rst, requirements.dev.txt, requirements.txt, setup.py, src/aioprometheus/__init__.py, src/aioprometheus/pusher.py, src/aioprometheus/service.py
Includes:
- Documentation update calling out the `aiohttp` extra for both the `Service` and `Pusher` features
- Import guards in `pusher` and `service`
- Runtime checks in the `Pusher` and `Service` initializers, to retain consistency in the top-level API
- Quoted type annotations where `aiohttp.web.*` might not be available
- Version bump to 19.11.0
---
@claws let me know if there is anything I missed or if you have any concerns, thanks! :)
=> Make aiohttp dependency optional

README.rst, docs/_static/custom.css, docs/index.rst
- Update the build status badge (on README and docs main page) to refer to the Github Action build result.
- Add black code format badge to README to make it consistent with Sphinx docs main page.
- Reduce highlighted code examples font size in Sphinx docs to reduce likelihood that horizontal scrollbars are shown.
=> Update CI badge

src/aioprometheus/decorators.py, tests/test_decorators.py
Now you can use same decorator for regular function
Also fixed issue with missed finally https://github.com/claws/aioprometheus/issues/47
=> Made @timer decorator works with both coroutines and regular functions

.github/workflows/ci.yml, .readthedocs.yml, CHANGELOG.md, Makefile, README.rst, docs/index.rst, docs/user/index.rst, examples/frameworks/fastapi-example.py, examples/frameworks/fastapi-middleware.py, examples/frameworks/quart-middleware.py, requirements.dev.txt, setup.py, src/aioprometheus/__init__.py, src/aioprometheus/asgi/middleware.py, src/aioprometheus/asgi/quart.py, src/aioprometheus/asgi/starlette.py, tests/test_aiohttp.py, tests/test_dist.bash, tests/test_export.py, tests/test_fastapi.py, tests/test_formats_binary.py, tests/test_negotiate.py, tests/test_pusher.py, tests/test_quart.py, tests/test_renderer.py
This change add an ASGI middleware to simplify use in Starlette, FastAPI and Quart web applications.
- Adds a asgi sub-package
- Updates unit tests
- Updates documentation
- Updates examples
- Updates README
- Adds new optional extra dependencies of ``starlette`` and ``quart``.
- Updates unit tests to gracefully handle when optional extras are not present.
=> Add ASGI middleware support

.github/workflows/ci.yml, CHANGELOG.md, Makefile, README.rst, docs/index.rst
This change updates the CI pipeline to upload code coverage report to codecov which allows code coverage to be tracked over time.
Updated the Makefile 'coverage' rule to produce the XML data expected by the codecov uploader.
Updated docs to display a code coverage status badge provided by codecov.
=> Update CI to upload coverage data to codecov

.readthedocs.yml
RTD reports an error as it only supports python versions up to 3.8.
=> Fix Python version in ReadTheDocs config file

.readthedocs.yml
Update the RTD configuration file to v2.
List the development requirements file so that RTD installs those items which should allow the build to complete as sphinx_material will then be found.
=> Update RTD config to version 2 format

examples/service/app-service-example.py, src/aioprometheus/asgi/middleware.py, src/aioprometheus/histogram.py
The user-specified registry was not passed to the middleware collectors,
so the default registry was always used.
The user-specified registry is now passed to the collectors. If the user
does not specify a registry the default registry will be used.
Fixes #70
=> Use specified registry in middleware collectors

src/aioprometheus/asgi/middleware.py
This minor addition to the `Middleware` class allows `const_labels` to be provided and passed to the counters created at construction.
Usage:
```python
app = FastAPI()
app.add_middleware(MetricsMiddleware, const_labels={"app": "webapi"})
```
=> Middleware const_labels argument

CHANGELOG.md, Makefile, docs/changes/index.rst, docs/dev/index.rst, docs/index.rst, docs/user/index.rst, setup.py, src/aioprometheus/__init__.py, src/aioprometheus/asgi/middleware.py
This change improves Starlette integration by fixing #72.
The change involves delaying creation of the middleware metrics until a call is made through to the middleware to update a  metric. This approached seemed like the best method for handling Starlette occasionally rebuilding the middleware stack - which, due to the middleware previously creating metrics in the ``__init__`` method, was the cause of the exceptions being triggered.
This change also makes minor tweaks to some project files and bumps the version in preparation for a new release. The tweaks are:
- include change log in docs.
- streamline Makefile rules
- Minor updates to dev docs
- include ``setup.py`` in style checks
- typos and grammar fixes
=> Improve Starlette integration, fixes #72

src/aioprometheus/pusher.py, tests/test_pusher.py
This adds support for passing in auth or timeout arguments to aiohttp.
=> #31 Adding support for aiohttp client args via pusher kwargs

requirements.txt, src/aioprometheus/collectors.py, src/aioprometheus/metricdict.py, tests/test_metricdict.py
* Use orjson as its much faster than the standard python json library.
* Drop object_pairs_hook when decoding keys as orjson interface does not support it.
A simple benchmark (there are plenty of others available on the internet):
```
In [1]: import json, orjson
In [2]: test_dict = {'bfdfsd': 223, 'afdsfds': '1freresr', '1':4, '3': '434w3', 'gfdgd': 'trttdrfg' }
In [3]: timeit json.loads(json.dumps(test_dict, sort_keys=True))
4.98 µs ± 78.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
In [4]: timeit orjson.loads(orjson.dumps(test_dict, option=(orjson.OPT_SORT_KEYS|orjson.OPT_NON_STR_KEYS)))
778 ns ± 2.09 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
In [5]: timeit orjson.loads(orjson.dumps(test_dict, option=orjson.OPT_SORT_KEYS))
692 ns ± 13.9 ns per loop …
```
=> Use orjson

.github/workflows/scheduled.yml, CHANGELOG.md, tests/test_pusher.py, tests/test_quart.py
Add a scheduled CI job to run periodically that should help identify when dependencies API's change.
Prepare for next release by updating change log, bumping version, fixing/updating some unit tests.
=> Add scheduled build and release prep

examples/decorators/decorator_count_exceptions.py, examples/decorators/decorator_inprogress.py, examples/decorators/decorator_timer.py, examples/service/app-service-example.py, requirements.dev.txt, src/aioprometheus/__init__.py, src/aioprometheus/asgi/middleware.py, src/aioprometheus/collectors.py, src/aioprometheus/mypy_types.py, src/aioprometheus/renderer.py, src/aioprometheus/service.py, tests/test_aiohttp.py, tests/test_dist.bash
- fixed aiohttp deprecation warnings. Affected files:
- src/aioprometheus/service.py
- tests/test_aiohttp.py
- fix pylint warnings. Affected files:
- examples/service/app-service-example.py
- examples/decorators/decorator_count_exceptions.py
- examples/decorators/decorator_inprogress.py
- examples/decorators/decorator_timer.py
- src/aioprometheus/mypy_types.py
- src/aioprometheus/collectors.py
- src/aioprometheus/renderer.py
- src/aioprometheus/asgi/middleware.py
- incorporates #94 (fixes #93) which supports websockets in asgi frameworks. Affected files:
- src/aioprometheus/service.py
- bump version to 23.12.0
=> Address deprecation warnings and fix websockets in asgi
